version: 2

sources:
  - name: silver
    schema: silver
    tables:
      - name: raw_obs
      - name: raw_obs__filetype
      - name: raw_obs__signatures
      - name: raw_obs__signatures__certs
      - name: batch_info
      - name: metadata_coff_file
      - name: metadata_elf_file
      - name: metadata_java_file
      - name: metadata_js_file
      - name: metadata_mach_o_file
      - name: metadata_native_lib_file
      - name: metadata_ole_file
      - name: metadata_pe_file
      - name: metadata_uimage_file
