name: eyeon_gold
version: 0.1.0
config-version: 2

profile: eyeon_gold

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  eyeon_gold:
    +materialized: view
    staging:
      +materialized: view
      +schema: gold_staging
    gold:
      +materialized: table
      +schema: gold
    certs:
      staging:
        +schema: staging
      intermediate:
        +schema: intermediate
      marts:
        +schema: gold

vars:
  eyeon_dataset_root: "{{ env_var('EYEON_DATASET_ROOT', '~/data/eyeon') }}"
